SitioPC/Models/productos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SitioPC.Models
{
    public class productos
    {        
        public int? Id { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Procesador")]
        public string procesador { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Gráficos")]
        public string graficos { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "RAM")]
        public string ram { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Pantalla")]
        public string pantalla { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Almacenamiento")]
        public string almacenamiento { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Bateria")]
        public string bateria { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Sistema Operativo")]
        public string so { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Audio")]
        public string audio { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Puertos")]
        public string puertos { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Conectividad")]
        public string conectividad { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Precio")]
        public decimal precio { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Existencias")]
        public int existencias { get; set; }
        
        [Display(Name = "Img")]
        public byte[] img { get; set; }

    }
}

SitioPC/Controllers/CarritoController.cs
using SitioPC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace SitioPC.Controllers
{
    [RequireHttps]
    public class CarritoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpPost]
        public JsonResult AgregaCarrito(int? id, int cantidad)
        {
            if (Session["carrito"] == null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                compras.Add(new CarritoItem(db.productos.Find(id), cantidad));
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1) 
                { 
                    compras.Add(new CarritoItem(db.productos.Find(id), cantidad));
                }
                else 
                { 
                    compras[IndexExistente].Cantidad += cantidad;
                    Session["carrito"] = compras;
                }
            }
            return Json(new { response = true }, JsonRequestBehavior.AllowGet);
        }

        // GET: Carrito
        //Agregar productos a la lista de carrito
        [HttpGet]
        public ActionResult AgregaCarrito()
        {           
            return View();
        }

        //Eliminar un producto de la lista de carrito
        public ActionResult Delete(int? id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            compras.RemoveAt(getIndex(id));

            return View("AgregaCarrito");
        }

        [Authorize(Roles = "Cliente"), RequireHttps]
        //Logica para finalizar la compra del cliente
        public ActionResult FinalizaCompra()
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            if (compras != null && compras.Count>0)
            {
                venta nuevaVenta = new venta();                
                nuevaVenta.fecha = DateTime.Now;
                nuevaVenta.ApplicationUserId = User.Identity.GetUserId();
                nuevaVenta.total = compras.Sum(x => x.Producto.precio * x.Cantidad);
                nuevaVenta.ApplicationUserName= User.Identity.GetUserName();

                nuevaVenta.ventadetalle = (from producto in compras
                                           select new ventadetalle
                                           {
                                               productosId = producto.Producto.Id,                                               
                                               nombre = producto.Producto.nombre,
                                               cantidad = producto.Cantidad,
                                               precio = producto.Producto.precio,
                                               subtotal = producto.Cantidad * producto.Producto.precio                                               
                                           }).ToList();

                db.venta.Add(nuevaVenta);                
                db.SaveChanges();                                
                Session["carrito"] = new List<CarritoItem>();
            }

            return View();
        }

        //Traer index para saber si ya existe el producto en la lista de carrito
        private int getIndex(int? id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compras.Count; i++)
            {
                if (compras[i].Producto.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

SitioPC/Controllers/productosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using SitioPC.Models;
using System.Web.Helpers;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace SitioPC.Controllers
{
    [Authorize, RequireHttps]
    public class productosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: productos        
        public ActionResult Index()
        {          
            return View(db.productos.ToList());
        }

        // GET: Lista
        [AllowAnonymous]
        public ActionResult Lista()
        {
            return View(db.productos.ToList());
        }

        // GET: productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: productos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nombre,procesador,graficos,ram,pantalla,almacenamiento,bateria,so,audio,puertos,conectividad,precio,existencias,img")] productos productos)
        {
            HttpPostedFileBase FileBase = Request.Files[0];

            if (FileBase.ContentLength == 0)
            {
                ModelState.AddModelError("Imagen","Seleccione una imagen para el producto");
            }
            else
            {
                if (FileBase.FileName.EndsWith(".png") || FileBase.FileName.EndsWith(".PNG"))
                {
                    WebImage image = new WebImage(FileBase.InputStream);
                    productos.img = image.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Solo se admiten imagenes con formato .png");
                }
                
            }            

            if (ModelState.IsValid)
            {
                db.productos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        // GET: productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,nombre,procesador,graficos,ram,pantalla,almacenamiento,bateria,so,audio,puertos,conectividad,precio,existencias,img")] productos productos)
        {
            //byte[] imagenActual = null;
            productos _productos = new productos();

            HttpPostedFileBase FileBase = Request.Files[0];
            if (FileBase.ContentLength == 0)
            {
                _productos = db.productos.Find(productos.Id);
                productos.img = _productos.img;
            }else
            {
                if (FileBase.FileName.EndsWith(".png") || FileBase.FileName.EndsWith(".PNG"))
                {
                    WebImage image = new WebImage(FileBase.InputStream);
                    productos.img = image.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Solo se admiten imagenes con formato .png");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(_productos).State = EntityState.Detached;
                db.Entry(productos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productos);
        }

        // GET: productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            productos productos = db.productos.Find(id);
            db.productos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        public ActionResult getImage(int? id)
        {
            productos productoK = db.productos.Find(id);
            byte[] byteImage = productoK.img;

            MemoryStream memoryStream = new MemoryStream(byteImage);
            Image image = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();
            image.Save(memoryStream, ImageFormat.Png);
            memoryStream.Position = 0;

            return File(memoryStream,"image/png");
        }
    }
}

SitioPC/Views/productos/Create.cshtml
@model SitioPC.Models.productos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center text-white pt-3">Agregar nuevo producto</h2>


@using (Html.BeginForm("Create","productos",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    <div class="container-fluid text-white pt-4">
        <form>
            <div class="row">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="col-md-6">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese nombre del producto" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.procesador, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.procesador, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese nombre del procesador" } })
                        @Html.ValidationMessageFor(model => model.procesador, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.graficos, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.graficos, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese el nombre de la tarjeta grafica" } })
                        @Html.ValidationMessageFor(model => model.graficos, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.ram, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.ram, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese la cantidad de RAM" } })
                        @Html.ValidationMessageFor(model => model.ram, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.pantalla, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.pantalla, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese el tipo y resolución de pantalla" } })
                        @Html.ValidationMessageFor(model => model.pantalla, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.almacenamiento, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.almacenamiento, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese el almacenamiento" } })
                        @Html.ValidationMessageFor(model => model.almacenamiento, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.bateria, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.bateria, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese las especificaciones de la batería" } })
                        @Html.ValidationMessageFor(model => model.bateria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.so, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col">
                        @Html.EditorFor(model => model.so, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese el Sistema Operativo" } })
                        @Html.ValidationMessageFor(model => model.so, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.audio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.audio, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese las especificaciones de audio" } })
                        @Html.ValidationMessageFor(model => model.audio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.puertos, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.puertos, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese las especificaciones de puertos" } })
                        @Html.ValidationMessageFor(model => model.puertos, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.conectividad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.conectividad, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese las especificaciones de conectividad" } })
                        @Html.ValidationMessageFor(model => model.conectividad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese el precio" } })
                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.existencias, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @Html.EditorFor(model => model.existencias, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese la cantidad que dispone" } })
                        @Html.ValidationMessageFor(model => model.existencias, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        @*Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control", @placeholder="Ingrese la URL de la imagen" } })*@
                        <input type="file" accept=".png,.PNG" name="imageload" required class="form-control"/>
                        @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group m-3">
                    <div class="col-md-offset-2 col-md-12">
                        <button type="submit" value="Agregar Producto" class="btn btn-success">Agregar Producto</button>
                    </div>
                </div>
                <div class="form-group mt-3">
                    <div class="col-md-offset-2 col-md-12">
                        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-outline-info" })
                    </div>
                </div>
            </div>
        </form>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SitioPC/Views/productos/Delete.cshtml
@model SitioPC.Models.productos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="p-3 text-white">
    <h2 class="text-warning">Eliminar producto</h2>
    <h3 class="text-danger">¿Seguro que quieres eliminar este producto?</h3>
    <div>

        <dl class="p-5">
            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.nombre):
            </dt>

            <dd>@Html.DisplayFor(model => model.nombre)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.procesador):
            </dt>

            <dd>@Html.DisplayFor(model => model.procesador)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.graficos):
            </dt>

            <dd>@Html.DisplayFor(model => model.graficos)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.ram):
            </dt>

            <dd>@Html.DisplayFor(model => model.ram)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.pantalla):
            </dt>

            <dd>@Html.DisplayFor(model => model.pantalla)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.almacenamiento):
            </dt>

            <dd>@Html.DisplayFor(model => model.almacenamiento)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.bateria):
            </dt>

            <dd>@Html.DisplayFor(model => model.bateria)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.so):
            </dt>

            <dd>@Html.DisplayFor(model => model.so)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.audio):
            </dt>

            <dd>@Html.DisplayFor(model => model.audio)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.puertos):
            </dt>

            <dd>@Html.DisplayFor(model => model.puertos)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.conectividad):
            </dt>

            <dd>@Html.DisplayFor(model => model.conectividad)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.precio):
            </dt>

            <dd>@Html.DisplayFor(model => model.precio)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.existencias):
            </dt>

            <dd>@Html.DisplayFor(model => model.existencias)</dd>

            <dt class="text-danger float-left pr-3">
                @Html.DisplayNameFor(model => model.img):
            </dt>

            <dd><img class="w-25" src="@Url.Action("getImage","productos",new { id=Model.Id})" /></dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-actions">
        <button type="submit" value="Delete" class="btn btn-danger ml-5">Eliminar</button>
        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-outline-info" })
    </div>
        }
    </div>
</div>

SitioPC/Views/productos/Lista.cshtml
@model IEnumerable<SitioPC.Models.productos>

@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="filtro">
    <ul>
        <li><img src="~/img/pc-filtro.PNG" alt=""></li>
        <li><img src="~/img/gamer-filtro.PNG" alt=""></li>
        <li><img src="~/img/laptop-filtro.PNG" alt=""></li>
    </ul>
</div>

<div class="conten-padre pb-5 justify-content-center row row-cols-md-4 flex-md-row w-100">
    @foreach (var item in Model)
    {
        if (item.existencias != 0) {
        <div class="contenedor">
            <div class="carta">
                <div class="lado frente">
                    <img src="@Url.Action("getImage", "productos", new { id = item.Id })" />
                </div>
                <div class="lado atras ficha-tecnica text-white bg-dark">
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.procesador):</b> @Html.DisplayFor(modelItem => item.procesador)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.graficos):</b> @Html.DisplayFor(modelItem => item.graficos)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.ram):</b> @Html.DisplayFor(modelItem => item.ram)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.pantalla):</b> @Html.DisplayFor(modelItem => item.pantalla)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.almacenamiento):</b> @Html.DisplayFor(modelItem => item.almacenamiento)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.bateria):</b> @Html.DisplayFor(modelItem => item.bateria)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.so):</b> @Html.DisplayFor(modelItem => item.so)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.audio):</b> @Html.DisplayFor(modelItem => item.audio)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.puertos):</b> @Html.DisplayFor(modelItem => item.puertos)</p>
                    <p><b class="text-success">@Html.DisplayNameFor(model => model.conectividad):</b> @Html.DisplayFor(modelItem => item.conectividad)</p>
                </div>
            </div>
            <div class="etiqueta">
                <h5 class="nom-producto">@Html.DisplayFor(modelItem => item.nombre)</h5>
                <h5 class="precio-producto"> @String.Format("{0:C}", item.precio) MX</h5>
                @*<h3 class="existencias">@Html.DisplayFor(modelItem => item.existencias)</h3><h3 class="existencias"> Existencias</h3><br>*@
                <h3 class="existencias text-warning">Disponible</h3><br />
                    <input class="input-group-sm numbers" type="number" id="quantity" value="1" min="1" max="@Html.DisplayFor(modelItem => item.existencias)">          
                    <a href="#" class="agregar btn btn-primary" title="add to shopping car">Agregar</a>
                              
                <h6 id="id">@item.Id</h6>
                @*Html.ActionLink("Agregar", "AgregaCarrito", "Carrito", new { Id = item.Id }, new { @class = "btn btn-primary" })*@
            </div>
        </div>
        } 
    }
</div>

@section Scripts
{
            <script>
            $(function () {
                $(".agregar").on("click", function (event){
                    event.preventDefault();
                    var ProductoId = $(this).parent().find("h6").text();
                    var cantidad = $(this).parent().find("input").val();

            $.ajax(
                {
                    url: "@Url.Action("AgregaCarrito", "Carrito")",
                    data:  { id: ProductoId, cantidad: cantidad },
                    type: "post",
                    success: function (response) {
                        window.location.href="@Url.Action("AgregaCarrito", "Carrito")";
                    },
                    error:function(err,error)
                    {
                        alert(error);
                    }
                }
                );
        });
        $(".numbers").keydown(function (e) {

            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 40]) !== -1 ||
                (e.keyCode == 65 && e.ctrlKey === true) ||
                (e.keyCode >= 35 && e.keyCode <= 39)) {
                    return;
                }

            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
    });
            </script>
        }
  